import type { Metadata } from "next";

import {
  Sidebar,
  SidebarFooter,
  SidebarContent,
  SidebarHeader,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { redirect } from "next/navigation";
import { getSessionData, logoutAction } from "../(common)/auth-actions";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionData = await getSessionData();
  if (!sessionData.isLoggedIn) {
    return redirect("/");
  }
  return (
    <>
      <Sidebar>
        <SidebarHeader>
          <h1 className="text-lg font-bold lg:text-2xl">Admin</h1>
        </SidebarHeader>
        <SidebarContent></SidebarContent>
        <SidebarFooter>
          <Button variant="outline" onClick={logoutAction}>
            Logout
          </Button>
        </SidebarFooter>
      </Sidebar>
      <main>
        <SidebarTrigger className="lg:hidden" />
        {children}
      </main>
    </>
  );
}
